### ISSUE TITLE
Automate and clean up assets/img/posts/*

### ISSUE THREAD

**Issue by mattpopovich** [mattpopovich/mattpopovich.com#6]
- [x] Automate making an image folder for posts
- [ ] And referencing images in those posts should use the pwd as that folder. 
  - Ex. Image placed at `img/posts/2020-hello-world/hello.jpg` should be able to be referenced as `![img](hello.jpg)` in `2020-hello-world` post.

**Comment by aviezab** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
solobearchn, @alejob, @DevonFulcher, @JamieJ1, @ramasai1, @g-tejas, @sprig, @metalicjames, @Esusi, @CS-Aditya-Rawat, @MaxfieldLewin, @fentas, @gbaf, @thomasjpfan, @amitrao999, @RandyR34, @brianmhunt, @Ledjob, @KaiWangCanada, @BillWCJ, @ProfitSwitcher, @Liiuc, @pgom, @beelzebubba, @stanleywu111, @iamdaiyuan, @Locky7, @haloboy777, @SamuelBonilla, @deVIAntCoDE, @luketaverne, @matthieuh, @hrishikeshio, @TimChen314, @ripley, @xyang532, @92nqb, @yilongwen, @TomMonkeyMan, @jonkiddy, @cyprienhenry, @jsfour, @ifvictr, @leogau, @q20, @skaslev, @will123195, @webolizzer, @brettlangdon, @nickkjordan

**Comment by mattpopovich** [comment]
I don't know if I like this anymore... cotes recently changed `img_path` to `media_subpath` so every post would need to get updated, which would change its last modified date (even though nothing materially changed). 
Plus, editors can't auto-complete the paths unless they are referenced from `/assets`... 
I think I'm going to close this issue for now.
